postgres:
  host: localhost
  port: 5431
  user: test
  password: test
  dbname: mocha
dynamo:
  reset: true
  host: "http://localhost"
  port: 8008
  region: "ap-northeast-2"
  table:
    message: "messages"
mocha:
  port: 3100
cache:
  port: 26379
  host: "localhost"
rest:
  port: 3000